# Generated by Django 4.2 on 2024-04-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_methode',
            new_name='payment_method',
        ),
    ]
