# Generated by Django 4.2 on 2024-04-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_payment_methode_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'участник'), ('MODERATOR', 'модератор')], default='MEMBER', max_length=9, verbose_name='роль'),
        ),
    ]
