# Generated by Django 4.2 on 2024-04-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'участник'), ('moderator', 'модератор')], default='member', max_length=9, verbose_name='роль'),
        ),
    ]
